# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.network :public_network, bridge: "wlo1", ip: "192.168.0.104", netmask: "255.255.255.0"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    config.vm.network "forwarded_port", guest: 9200, host: 9200
    config.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          sudo su && mkdir /root/.ssh && cp /home/vagrant/.ssh/authorized_keys /root/.ssh
        SHELL
    end
end
